spring:
  application:
    name: authorization
    
  datasource:
    url: jdbc:mysql://localhost:3306/authorization
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

security:
  oauth2:
    client:
      client-id: mobile
      client-secret: test

server:
   port: 9000
