spring:
  cloud:
    config:
      name: authorization
      uri: http://localhost:8888/
  
  datasource:
    url: jdbc:mysql://localhost:3306/authorization
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  security:
    oauth2:
      client:
        registration:
          client-id: mobile
          client-secret: test
keycloak:
  realm: Social-Network
  resource: Social-Network
  auth-server-url: http://localhost:8080/auth/
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username
  
server:
   port: 9090

