spring:
  cloud:
    config:
      name: authorization
      uri: http://localhost:8888/
  
  datasource:
    url: jdbc:mysql://localhost:3306/authorization
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  security:
    oauth2:
      client:
        registration:
            clientId: mobile
            clientSecret: test  
server:
   port: 9089
