spring:
  application:
    name: profile
    
  datasource:
    url: jdbc:mysql://localhost:3306/profile
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
keycloak:
  realm: Social-Network
  resource: Social-Network
  auth-server-url: http://localhost:8080/auth/
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username
  
server:
   port: 9001
