spring:
  application:
    name: zuul

server:
  port: 9999
  
zuul:
  routes: 
        profile-server:
          path: /profiles/**
          url: http://localhost:9001/profiles/
          service-id: PROFILE
          strip-prefix: true
        authorization:
          path: /users/**
          url: http://localhost:9000/users/
          service-id: AUTHORIZATION
          strip-prefix: true
        actuator:
          path: /actuator/**
          url: http://localhost:9060/actuator/
          service-id: ACTUATOR
          strip-prefix: true
